import Foundation

// Emit.swift — AST → Swift source. Port of swiftemit.go.
// Byte-for-byte faithful port of the Go emitter (cross-binding golden, T1.4).
// (emitPlist lives in Plist.swift.)

// emitSwift turns parsed operations into one PalbaseGenerated.swift.
//
// The Swift file is types + endpoint methods only; the runtime config
// (url / apiKey / oauth) ships separately as the per-env Palbase-Info.plist.
func emitSwift(_ ops: [SwiftOp], rooms: [SwiftRoom] = []) -> String {
    // Reserved namespaces on `pb`: SDK-owned surfaces. An endpoint whose top
    // segment collides with one would shadow it, so skip those endpoints and
    // emit a visible comment so the developer knows what was dropped.
    let reserved: Set<String> = [
        "auth",
        "analytics",
        "flags",
        "realtime",
        "notifications",
        "perf",
        "messaging",
        "purchases",
        "debug",
    ]
    var usable: [SwiftOp] = []
    var swiftSkippedNS: [String] = []
    var swiftSeenSkip: Set<String> = []
    for op in ops {
        let segs = opSegments(op.operationID)
        if segs.count > 0 && reserved.contains(segs[0].lowercased()) {
            let ns = segs[0].lowercased()
            if !swiftSeenSkip.contains(ns) {
                swiftSeenSkip.insert(ns)
                swiftSkippedNS.append(ns)
            }
            continue
        }
        usable.append(op)
    }
    swiftSkippedNS.sort()

    var b = ""
    b += "// Generated by palbase-swiftgen from .palbase/openapi.json — DO NOT EDIT.\n"
    b += "// Commit this file. Regenerate it with `palbase spec` after every deploy.\n"
    b += "import Foundation\n"
    b += "import Palbe\n\n"

    b += "// MARK: - Request / response types\n\n"
    b += emitTypeTree(usable)

    b += "\n// MARK: - Namespaced calls (pb.*)\n\n"
    for ns in swiftSkippedNS {
        b += "// codegen: skipped reserved namespace \"" + ns + "\" (SDK-owned)\n"
    }
    b += emitNamespaceTree(usable)

    // Rooms last, and only when there are any: a project that never declared one
    // must get the file it got before (NFR-004).
    if !rooms.isEmpty {
        b += "\n// MARK: - Rooms (@Room)\n\n"
        for room in rooms {
            b += emitRoom(room) + "\n"
        }
    }

    return b
}

// MARK: - rooms

/// The Swift type name for a room: `ai:{sessionId}` → `AiSessionIdRoom`.
private func roomTypeName(_ pattern: String) -> String {
    return typeNameOf(pattern) + "Room"
}

/// Emit one room as a type an app can hold, with its events and messages as
/// enums whose payloads are real structs.
///
/// The shape is chosen so that **an app writes no strings and no types of its
/// own**: the pattern, the event names and the message names all live here, and
/// the only thing the app supplies is the `{param}` values. `decode` and
/// `encode` are generated for the same reason — without them the app is back to
/// matching event names by hand, which is the DX this replaces.
private func emitRoom(_ room: SwiftRoom) -> String {
    let name = roomTypeName(room.pattern)
    var lines: [String] = []
    lines.append("public nonisolated struct " + name + ": PBRoom {")

    // The pattern is the room's identity and the ONE place the raw string lives.
    lines.append(indent(1) + "public static let pattern = " + swiftStringLiteral(room.pattern))

    for p in room.params {
        lines.append(indent(1) + "public let " + identOf(p) + ": String")
    }
    if room.params.isEmpty {
        lines.append(indent(1) + "public init() {}")
    } else {
        let params = room.params.map { identOf($0) + ": String" }.joined(separator: ", ")
        lines.append(indent(1) + "public init(" + params + ") {")
        for p in room.params {
            lines.append(indent(2) + "self." + unbacktick(identOf(p)) + " = " + identOf(p))
        }
        lines.append(indent(1) + "}")
    }

    // The topic, built by the compiler. An app that has to interpolate this by
    // hand can typo it, and a typo'd topic is a room that silently never fills.
    lines.append(indent(1) + "public var topic: String {")
    var expr = ""
    for seg in room.pattern.split(separator: ":", omittingEmptySubsequences: false) {
        let s = String(seg)
        if !expr.isEmpty { expr += ":" }
        if s.hasPrefix("{"), s.hasSuffix("}"), s.count > 2 {
            expr += "\\(" + identOf(String(s.dropFirst().dropLast())) + ")"
        } else {
            expr += s
        }
    }
    lines.append(indent(2) + "return \"" + expr + "\"")
    lines.append(indent(1) + "}")
    lines.append("")

    // ── events (server → device) ──
    for e in room.events {
        lines.append(contentsOf: structLines(roomPayloadTypeName(e.name, "Event"), e.schema.props, 1))
    }
    lines.append(indent(1) + "public enum Event: Sendable {")
    for e in room.events {
        lines.append(indent(2) + "case " + identOf(e.name) + "(" + roomPayloadTypeName(e.name, "Event") + ")")
    }
    if room.events.isEmpty {
        // An empty Swift enum can never be instantiated, which is the honest
        // model of a room that sends nothing — but it must still compile.
        lines.append(indent(2) + "// this room declares no events")
    }
    lines.append(indent(1) + "}")
    lines.append("")

    // The names RoomHandle subscribes to. Without this the handle would have to
    // guess, and a room's events are exactly the thing it must not guess at.
    lines.append(indent(1) + "public static let eventNames: [String] = [" +
        room.events.map { swiftStringLiteral($0.name) }.joined(separator: ", ") + "]")
    lines.append("")
    lines.append(indent(1) + "public static func decode(event: String, data: Data) throws -> Event? {")
    if room.events.isEmpty {
        lines.append(indent(2) + "_ = (event, data)")
        lines.append(indent(2) + "return nil")
    } else {
        lines.append(indent(2) + "switch event {")
        for e in room.events {
            lines.append(indent(2) + "case " + swiftStringLiteral(e.name) + ":")
            lines.append(indent(3) + "return .\(identOf(e.name))(try JSONDecoder.palbaseDefault.decode(" +
                roomPayloadTypeName(e.name, "Event") + ".self, from: data))")
        }
        lines.append(indent(2) + "default:")
        // An unknown event is a SERVER that moved ahead of this client, not an
        // error: nil lets the app ignore it instead of tearing the room down.
        lines.append(indent(3) + "return nil")
        lines.append(indent(2) + "}")
    }
    lines.append(indent(1) + "}")
    lines.append("")

    // ── messages (device → server) ──
    for m in room.messages {
        // requestSide: these go OUT, so the snake_case gate applies — an
        // uppercase wire key would be silently dropped by the SDK's encoder.
        lines.append(contentsOf: structLines(roomPayloadTypeName(m.name, "Message"), m.schema.props, 1, requestSide: true))
    }
    lines.append(indent(1) + "public enum Send: Sendable {")
    for m in room.messages {
        lines.append(indent(2) + "case " + identOf(m.name) + "(" + roomPayloadTypeName(m.name, "Message") + ")")
    }
    if room.messages.isEmpty {
        lines.append(indent(2) + "// this room accepts no client messages")
    }
    lines.append(indent(1) + "}")
    lines.append("")

    lines.append(indent(1) + "public static func encode(_ message: Send) throws -> (event: String, data: Data) {")
    if room.messages.isEmpty {
        lines.append(indent(2) + "_ = message")
        lines.append(indent(2) + "throw PBRoomError.noMessagesDeclared(pattern)")
    } else {
        lines.append(indent(2) + "switch message {")
        for m in room.messages {
            lines.append(indent(2) + "case .\(identOf(m.name))(let value):")
            lines.append(indent(3) + "return (" + swiftStringLiteral(m.name) +
                ", try JSONEncoder.palbaseDefault.encode(value))")
        }
        lines.append(indent(2) + "}")
    }
    lines.append(indent(1) + "}")
    lines.append("}")
    return lines.joined(separator: "\n") + "\n"
}

private func roomPayloadTypeName(_ name: String, _ suffix: String) -> String {
    return typeNameOf(name) + suffix
}

// `internal`: shared with the purchases-catalog emitter (Purchases.swift).
func swiftStringLiteral(_ s: String) -> String {
    // Mirrors Go's strconv.Quote for the printable-ASCII inputs the emitter
    // sees (wire keys / codes / path segments): double-quoted with backslash
    // escapes for the special characters.
    var out = "\""
    for ch in s {
        switch ch {
        case "\"": out += "\\\""
        case "\\": out += "\\\\"
        case "\n": out += "\\n"
        case "\r": out += "\\r"
        case "\t": out += "\\t"
        default: out.append(ch)
        }
    }
    out += "\""
    return out
}

// --- Naming -----------------------------------------------------------------

private func opSegments(_ opID: String) -> [String] {
    return opID.split(separator: ".", omittingEmptySubsequences: true).map(String.init)
}

private func typeNameOf(_ s: String) -> String { return sanitize(s, true) }
// `internal` (not private): the purchases-catalog emitter in Purchases.swift needs the
// same identifier rules — one sanitizer, not two.
func identOf(_ s: String) -> String { return escapeKeyword(sanitize(s, false)) }

// typePrefix builds the PascalCase concatenation of all op-id segments.
private func typePrefix(_ opID: String) -> String {
    let segs = opSegments(opID)
    return segs.map { typeNameOf($0) }.joined()
}

private func requestTypeName(_ opID: String) -> String { return typePrefix(opID) + "Request" }
private func responseTypeName(_ opID: String) -> String { return typePrefix(opID) + "Response" }
private func errorEnumName(_ opID: String) -> String { return typePrefix(opID) + "Error" }
private func headersTypeName(_ opID: String) -> String { return typePrefix(opID) + "Headers" }
private func queryTypeName(_ opID: String) -> String { return typePrefix(opID) + "Query" }

private func sanitize(_ s: String, _ firstUpper: Bool) -> String {
    var parts: [String] = []
    var cur = ""
    for ch in s {
        if (ch >= "a" && ch <= "z") || (ch >= "A" && ch <= "Z") || (ch >= "0" && ch <= "9") {
            cur.append(ch)
        } else if !cur.isEmpty {
            parts.append(cur)
            cur = ""
        }
    }
    if !cur.isEmpty {
        parts.append(cur)
    }
    if parts.isEmpty {
        if firstUpper {
            return "Op"
        }
        return "op"
    }
    var res = ""
    for (i, p) in parts.enumerated() {
        if i == 0 && !firstUpper {
            res += p.prefix(1).lowercased() + p.dropFirst()
        } else {
            res += p.prefix(1).uppercased() + p.dropFirst()
        }
    }
    var out = res
    let first = out.unicodeScalars.first!
    if first >= "0" && first <= "9" {
        out = "_" + out
    }
    return out
}

private let swiftKeywords: Set<String> = [
    "class", "struct", "enum", "func", "let", "var",
    "return", "if", "else", "for", "while", "switch",
    "case", "default", "import", "public", "private",
    "internal", "protocol", "extension", "self", "init",
    "deinit", "in", "where", "as", "is", "try",
    "throw", "throws", "async", "await", "nil", "true",
    "false", "guard", "defer", "do", "catch", "repeat",
    "operator", "associatedtype", "any",
]

private func escapeKeyword(_ id: String) -> String {
    if swiftKeywords.contains(id) {
        return "`" + id + "`"
    }
    return id
}

func unbacktick(_ s: String) -> String { return s.replacingOccurrences(of: "`", with: "") }

// encoderCanProduce reports whether the SDK's `.convertToSnakeCase` ENCODER can
// emit this wire key at all.
//
// It cannot, ever, if the key carries an uppercase letter: that strategy
// lowercases everything it touches, so no Swift identifier — and no explicit
// CodingKey either — can come out as `gapMs`. MEASURED 2026-08-30 rather than
// assumed: with the strategy set, `gapMs` encodes to `gap_ms` both with and
// without `enum CodingKeys: String, CodingKey { case gapMs = "gapMs" }`. The
// strategy is applied to the CodingKey's stringValue, which is why the usual
// escape hatch is not one here.
//
// This is deliberately the CONSERVATIVE half of the question. Exotic keys with
// doubled or interior underscores can also fail to round-trip, and those slip
// through — but every key this rejects is genuinely unreachable, so there are no
// false alarms. `snakeCaseRoundTrips` above answers the DECODE direction, where
// `ident == key` is enough; on the encode side it is not, and conflating the two
// is exactly how a request field came to be silently dropped.
private func encoderCanProduce(_ key: String) -> Bool {
    return !key.contains(where: { $0.isUppercase })
}

// snakeHint renders the obvious rename so the message can show it rather than
// describe it. Not Foundation's algorithm — a suggestion, not a contract.
private func snakeHint(_ key: String) -> String {
    var out = ""
    for ch in key {
        if ch.isUppercase {
            if !out.isEmpty && !out.hasSuffix("_") { out.append("_") }
            out.append(Character(ch.lowercased()))
        } else {
            out.append(ch)
        }
    }
    return out
}

// swiftIdentLiteralSafe keeps a wire key readable inside a message without
// letting a quote in it break the literal that carries it.
private func swiftIdentLiteralSafe(_ s: String) -> String {
    return "`" + s.replacingOccurrences(of: "`", with: "") + "`"
}


// snakeCaseRoundTrips reports whether the SDK's `.convertFromSnakeCase` decoder
// would map the wire key back to exactly `ident` (and `.convertToSnakeCase`
// would produce `key` from `ident`) — i.e. NO explicit CodingKey is needed.
// Mirrors Foundation's documented convertFromSnakeCase including the
// leading/trailing-underscore passthrough.
private func snakeCaseRoundTrips(_ ident: String, _ key: String) -> Bool {
    if ident == key {
        return true // already identical (e.g. `platform`, an escaped keyword)
    }
    if !key.contains("_") {
        return false // no underscores → strategy leaves it as-is ≠ ident
    }
    // Preserve leading/trailing underscores exactly as Foundation does.
    let chars = Array(key)
    var lead = 0
    while lead < chars.count && chars[lead] == "_" {
        lead += 1
    }
    var trail = 0
    while trail < chars.count - lead && chars[chars.count - 1 - trail] == "_" {
        trail += 1
    }
    let core = String(chars[lead..<(chars.count - trail)])
    if core.isEmpty {
        return false
    }
    let parts = core.split(separator: "_", omittingEmptySubsequences: false).map(String.init)
    var b = ""
    b += String(chars[0..<lead])
    for (i, p) in parts.enumerated() {
        if p.isEmpty {
            // Consecutive underscores: Foundation keeps an empty component,
            // which can't round-trip cleanly → force a mismatch (emit a key).
            return false
        }
        if i == 0 {
            b += p.lowercased()
        } else {
            b += p.prefix(1).uppercased() + p.dropFirst().lowercased()
        }
    }
    b += String(chars[(chars.count - trail)...])
    return b == ident
}

private func indent(_ d: Int) -> String { return String(repeating: "    ", count: d) }

// --- Top-level Request / Response / Error types ----------------------------

private func emitTypeTree(_ ops: [SwiftOp]) -> String {
    var lines: [String] = []
    for op in ops {
        var emitted = false
        if let input = op.input {
            lines.append(contentsOf: topLevelDeclLines(requestTypeName(op.operationID), input, requestSide: true))
            emitted = true
        }
        if let output = op.output {
            if emitted {
                lines.append("")
            }
            lines.append(contentsOf: topLevelDeclLines(responseTypeName(op.operationID), output))
            emitted = true
        } else if op.upload != nil {
            // An @Upload op ALWAYS surfaces a typed completion Response. When the
            // backend declares the @Upload 200 with no JSON body, emit an empty
            // Codable struct so the `Response` typealias never dangles.
            if emitted {
                lines.append("")
            }
            lines.append("public nonisolated struct " + responseTypeName(op.operationID) + ": Codable, Sendable {")
            lines.append("}")
            emitted = true
        }
        if let headers = op.headers {
            if emitted {
                lines.append("")
            }
            lines.append(contentsOf: headerStructLines(headersTypeName(op.operationID), headers))
            emitted = true
        }
        if let query = op.query {
            if emitted {
                lines.append("")
            }
            lines.append(contentsOf: queryStructLines(queryTypeName(op.operationID), query))
            emitted = true
        }
        // EVERY op gets a PBError error enum — even with zero inferred errors.
        if emitted {
            lines.append("")
        }
        lines.append(contentsOf: topLevelErrorEnumLines(errorEnumName(op.operationID), op.errors))
        lines.append("")
        // Per-op endpoint struct.
        lines.append(contentsOf: endpointStructLines(op))
        lines.append("")
    }
    return lines.joined(separator: "\n")
}

private func endpointStructName(_ opID: String) -> String { return typePrefix(opID) + "Endpoint" }

// pathSegmentsExpr renders the op's wire path as a Swift `[PBPathSegment]`
// array literal: fixed segments become bare string literals, and `{name}`
// path-param segments become `.param(<ident>)`.
private func pathSegmentsExpr(_ path: String) -> String {
    let raw = path.components(separatedBy: "/")
    var segs: [String] = []
    for seg in raw {
        if seg.isEmpty {
            continue
        }
        let chars = Array(seg)
        if chars.count >= 2 && chars[0] == "{" && chars[chars.count - 1] == "}" {
            let name = String(chars[1..<(chars.count - 1)])
            if name.isEmpty {
                continue
            }
            segs.append(".param(" + identOf(name) + ")")
        } else {
            segs.append(swiftStringLiteral(seg))
        }
    }
    return "[" + segs.joined(separator: ", ") + "]"
}

// endpointStructLines emits one `public nonisolated struct <Op>Endpoint` that
// adopts PBEndpoint (op has a 200 body) or PBVoidEndpoint (no body).
private func endpointStructLines(_ op: SwiftOp) -> [String] {
    // An @Upload op adopts a DIFFERENT protocol. Must be checked FIRST.
    if op.upload != nil {
        return uploadEndpointStructLines(op)
    }

    let name = endpointStructName(op.operationID)
    let hasBody = op.output != nil

    var lines: [String] = []
    if op.sse {
        // An @Sse op adopts PBSseEndpoint and names its frame type `Element`,
        // not `Response`. The distinction is the whole point: a `Response`
        // endpoint reads the body ONCE, which on a streaming route means
        // blocking until the stream ends and then decoding the concatenation of
        // every frame as one document. Everything BELOW this (stored inputs,
        // pbRequest) is identical — only the contract differs.
        lines.append("public nonisolated struct " + name + ": PBSseEndpoint {")
        lines.append(indent(1) + "public typealias Element = " + responseTypeName(op.operationID))
    } else if hasBody {
        lines.append("public nonisolated struct " + name + ": PBEndpoint {")
        lines.append(indent(1) + "public typealias Response = " + responseTypeName(op.operationID))
    } else {
        lines.append("public nonisolated struct " + name + ": PBVoidEndpoint {")
    }
    lines.append(indent(1) + "public typealias Failure = " + errorEnumName(op.operationID))

    // Stored inputs, in the same order the namespace method passes them.
    for p in op.pathParams {
        lines.append(indent(1) + "let " + identOf(p) + ": String")
    }
    if op.input != nil {
        lines.append(indent(1) + "let input: " + requestTypeName(op.operationID))
    }
    if op.query != nil {
        lines.append(indent(1) + "let query: " + queryTypeName(op.operationID))
    }
    if op.headers != nil {
        lines.append(indent(1) + "let headers: " + headersTypeName(op.operationID))
    }

    // pbRequest: PBRequest(.<method>, [<segments>], body:?, query:?, headers:?)
    var httpMethod = op.method
    if httpMethod == "" {
        httpMethod = "POST"
    }
    var httpPath = op.path
    if httpPath == "" {
        httpPath = "/" + op.operationID.replacingOccurrences(of: ".", with: "/")
    }
    var args = ["." + httpMethod.lowercased(), pathSegmentsExpr(httpPath)]
    if op.input != nil {
        args.append("body: input")
    }
    if op.query != nil {
        args.append("query: query")
    }
    if op.headers != nil {
        args.append("headers: headers.asHeaderDict()")
    }
    lines.append(indent(1) + "public var pbRequest: PBRequest { PBRequest(" + args.joined(separator: ", ") + ") }")
    lines.append("}")
    return lines
}

// uploadEndpointStructLines emits one `public nonisolated struct <Op>Endpoint`
// that adopts `PBUploadEndpoint`.
private func uploadEndpointStructLines(_ op: SwiftOp) -> [String] {
    let name = endpointStructName(op.operationID)

    var lines: [String] = []
    lines.append("public nonisolated struct " + name + ": PBUploadEndpoint {")
    lines.append(indent(1) + "public typealias Response = " + responseTypeName(op.operationID))
    lines.append(indent(1) + "public typealias Failure = " + errorEnumName(op.operationID))

    for p in op.pathParams {
        lines.append(indent(1) + "let " + identOf(p) + ": String")
    }
    if op.input != nil {
        lines.append(indent(1) + "let input: " + requestTypeName(op.operationID))
    }

    // authorizeRequest: the pre-flight is always a POST.
    var httpPath = op.path
    if httpPath == "" {
        httpPath = "/" + op.operationID.replacingOccurrences(of: ".", with: "/")
    }
    var args = [".post", pathSegmentsExpr(httpPath)]
    if op.input != nil {
        args.append("body: input")
    }
    lines.append(indent(1) + "public var authorizeRequest: PBRequest { PBRequest(" + args.joined(separator: ", ") + ") }")
    lines.append("}")
    return lines
}

// topLevelDeclLines renders one top-level type for an operation side.
private func topLevelDeclLines(_ name: String, _ s: SwiftSchema, requestSide: Bool = false) -> [String] {
    if s.kind == "object" {
        return structLines(name, s.props, 0, requestSide: requestSide)
    }
    if s.kind == "array", let elem = s.elem?.value, elem.kind == "object", elem.props.count > 0 {
        let itemName = name + "Item"
        var lines = structLines(itemName, elem.props, 0, requestSide: requestSide)
        lines.append("")
        lines.append("public typealias " + name + " = [" + itemName + "]")
        return lines
    }
    return ["public typealias " + name + " = " + bareType(s)]
}

// headerStructLines emits the <Op>Headers struct PLUS an `asHeaderDict()` method.
private func headerStructLines(_ name: String, _ s: SwiftSchema) -> [String] {
    var lines = structLines(name, s.props, 0)
    // Drop the struct's closing brace so we can append the method inside.
    if let last = lines.last, last.trimmingCharacters(in: .whitespaces) == "}" {
        lines.removeLast()
    }
    lines.append(indent(1) + "public func asHeaderDict() -> [String: String] {")
    lines.append(indent(2) + "var out: [String: String] = [:]")
    for p in s.props {
        let ident = identOf(p.name)
        let key = swiftStringLiteral(p.name)
        let optional = !p.required || p.schema.nullable
        // Value expression: enum → .rawValue, string → itself.
        var valueExpr = ident
        if p.schema.kind == "enum" {
            valueExpr = ident + ".rawValue"
        }
        if optional {
            if p.schema.kind == "enum" {
                lines.append(indent(2) + "if let v = " + ident + " { out[" + key + "] = v.rawValue }")
            } else {
                lines.append(indent(2) + "if let v = " + ident + " { out[" + key + "] = v }")
            }
        } else {
            lines.append(indent(2) + "out[" + key + "] = " + valueExpr)
        }
    }
    lines.append(indent(2) + "return out")
    lines.append(indent(1) + "}")
    lines.append("}")
    return lines
}

// queryStructLines emits the <Op>Query struct (typed Codable fields).
private func queryStructLines(_ name: String, _ s: SwiftSchema) -> [String] {
    return structLines(name, s.props, 0)
}

// topLevelErrorEnumLines renders one `public enum <Prefix>Error: PBError` block.
private func topLevelErrorEnumLines(_ enumName: String, _ errs: [SwiftErrorDef]) -> [String] {
    var lines: [String] = []
    lines.append("public nonisolated enum " + enumName + ": PBError {")
    let fd = 1

    // `other` is reserved for the fallback case; a declared error whose name
    // sanitizes to it (or to a previous case's ident) is skipped with a comment.
    var seenIdent: [String: String] = ["other": "the other(BackendError) fallback"]
    var cases: [SwiftErrorDef] = []
    for e in errs {
        let ident = unbacktick(identOf(e.name))
        if let first = seenIdent[ident] {
            lines.append(indent(fd) + "// codegen: skipped declared error " +
                swiftStringLiteral(e.name) + " — collides with " + first +
                " (both map to Swift `" + ident + "`); it surfaces as .other at runtime")
            continue
        }
        seenIdent[ident] = swiftStringLiteral(e.name)
        cases.append(e)
    }

    // Per-case data payload structs / typealiases first.
    for e in cases {
        guard let data = e.data else {
            continue
        }
        let typeName = typeNameOf(e.name) + "Data"
        if data.kind == "object" {
            lines.append(contentsOf: structLines(typeName, data.props, fd))
        } else {
            lines.append(indent(fd) + "public typealias " + typeName + " = " + bareType(data))
        }
    }

    // case declarations — declared cases first, then the `.other` fallback.
    for e in cases {
        let caseName = identOf(e.name)
        if e.data != nil {
            lines.append(indent(fd) + "case " + caseName + "(" + typeNameOf(e.name) + "Data)")
        } else {
            lines.append(indent(fd) + "case " + caseName)
        }
    }
    lines.append(indent(fd) + "case other(BackendError)")

    // init(_ backend:) — pure code-switch mapping.
    if cases.isEmpty {
        lines.append(indent(fd) + "public nonisolated init(_ backend: BackendError) { self = .other(backend) }")
        lines.append("}")
        return lines
    }
    lines.append(indent(fd) + "public nonisolated init(_ backend: BackendError) {")
    lines.append(indent(fd + 1) + "guard case .server(let f) = backend else { self = .other(backend); return }")
    lines.append(indent(fd + 1) + "switch f.code {")
    for e in cases {
        let caseName = identOf(e.name)
        if e.data != nil {
            let typeName = typeNameOf(e.name) + "Data"
            lines.append(indent(fd + 1) + "case " + swiftStringLiteral(e.code) + ":")
            lines.append(indent(fd + 2) + "if let data = f.decodeData(" + typeName + ".self) { self = ." + caseName + "(data) } else { self = .other(backend) }")
        } else {
            lines.append(indent(fd + 1) + "case " + swiftStringLiteral(e.code) + ": self = ." + caseName)
        }
    }
    lines.append(indent(fd + 1) + "default: self = .other(backend)")
    lines.append(indent(fd + 1) + "}")
    lines.append(indent(fd) + "}")

    lines.append("}")
    return lines
}

private func structLines(_ name: String, _ props: [SwiftProp], _ depth: Int, requestSide: Bool = false) -> [String] {
    var lines: [String] = []
    lines.append(indent(depth) + "public nonisolated struct " + name + ": Codable, Sendable {")
    let fd = depth + 1

    struct Field {
        var ident: String
        var key: String
        var typ: String
        var optional: Bool
    }
    var fields: [Field] = []
    // Guard against identifier collision: keep the FIRST key for each ident.
    var seenIdent: [String: String] = [:]
    for p in props {
        let ident = identOf(p.name)
        if let firstKey = seenIdent[ident] {
            lines.append(indent(fd) + "// codegen: skipped duplicate key " +
                swiftStringLiteral(p.name) + " — collides with " + swiftStringLiteral(firstKey) +
                " (both map to Swift `" + unbacktick(ident) + "`)")
            continue
        }
        seenIdent[ident] = p.name
        // A request field the encoder cannot address is worse than a missing
        // one: the call compiles, runs, and the server quietly applies its
        // default. Refusing to COMPILE is the only honest option — a comment
        // would be read after the bug, not before it.
        if requestSide, !encoderCanProduce(p.name) {
            lines.append(indent(fd) + "#error(" + swiftStringLiteral(
                "palbase: this client cannot send the field " + swiftIdentLiteralSafe(p.name) +
                " of " + name + ". The SDK encodes request bodies with " +
                ".convertToSnakeCase, so an uppercase letter in a wire key can never be " +
                "produced — the field would be silently dropped and the server would apply " +
                "its default. Rename it to snake_case in the backend schema (for example " +
                snakeHint(p.name) + ") and re-run `palbase link`.") + ")")
            continue
        }
        let optional = !p.required || p.schema.nullable
        var (typ, nested) = fieldType(p.schema, p.name, fd, requestSide: requestSide)
        // A REQUEST field that is both optional and nullable carries three
        // intentions — omit, clear, set — and a plain Optional carries two.
        // Wrapping keeps "clear" expressible; see Nullable in GeneratedSupport.
        // Responses need no wrapper: nothing is omitted-vs-null from the caller's
        // side there, so they keep the plain Optional they always had.
        if requestSide, !p.required, p.schema.nullable {
            typ = "Nullable<" + typ + ">"
        }
        lines.append(contentsOf: nested)
        fields.append(Field(ident: ident, key: p.name, typ: typ, optional: optional))
    }
    for f in fields {
        var t = f.typ
        if f.optional {
            t += "?"
        }
        lines.append(indent(fd) + "public let " + f.ident + ": " + t)
    }
    // Memberwise init.
    var params: [String] = []
    for f in fields {
        var t = f.typ
        if f.optional {
            t += "? = nil"
        }
        params.append(f.ident + ": " + t)
    }
    lines.append(indent(fd) + "public init(" + params.joined(separator: ", ") + ") {")
    for f in fields {
        lines.append(indent(fd + 1) + "self." + f.ident + " = " + f.ident)
    }
    lines.append(indent(fd) + "}")
    // CodingKeys ONLY for the keys the SDK's coder strategy can't reconstruct.
    var needKeys = false
    for f in fields {
        if !snakeCaseRoundTrips(unbacktick(f.ident), f.key) {
            needKeys = true
            break
        }
    }
    if needKeys {
        lines.append(indent(fd) + "enum CodingKeys: String, CodingKey {")
        for f in fields {
            if snakeCaseRoundTrips(unbacktick(f.ident), f.key) {
                lines.append(indent(fd + 1) + "case " + f.ident)
            } else {
                lines.append(indent(fd + 1) + "case " + f.ident + " = \"" + f.key + "\"")
            }
        }
        lines.append(indent(fd) + "}")
    }
    lines.append(indent(depth) + "}")
    return lines
}

private func fieldType(_ s: SwiftSchema, _ fieldName: String, _ depth: Int, requestSide: Bool = false) -> (String, [String]) {
    switch s.kind {
    case "string":
        return ("String", [])
    case "number":
        return ("Double", [])
    case "integer":
        return ("Int", [])
    case "boolean":
        return ("Bool", [])
    case "any":
        return ("AnyCodableValue", [])
    case "enum":
        let typeName = typeNameOf(fieldName) + "Value"
        var decl = [indent(depth) + "public nonisolated enum " + typeName + ": String, Codable, Sendable {"]
        for c in s.enumVals {
            decl.append(indent(depth + 1) + "case " + identOf(c) + " = \"" + c + "\"")
        }
        decl.append(indent(depth) + "}")
        return (typeName, decl)
    case "array":
        let (elemType, nested) = fieldType(s.elem!.value, fieldName + "Item", depth, requestSide: requestSide)
        return ("[" + elemType + "]", nested)
    case "object":
        let typeName = typeNameOf(fieldName)
        return (typeName, structLines(typeName, s.props, depth, requestSide: requestSide))
    default:
        return ("AnyCodableValue", [])
    }
}

private func bareType(_ s: SwiftSchema) -> String {
    switch s.kind {
    case "string":
        return "String"
    case "number":
        return "Double"
    case "integer":
        return "Int"
    case "boolean":
        return "Bool"
    case "enum":
        return "String"
    case "array":
        return "[" + bareType(s.elem!.value) + "]"
    default:
        return "AnyCodableValue"
    }
}

// --- Namespace tree (pb.<ns>.<op>) ------------------------------------------

private final class NSNode {
    var path: [String]
    var children: [String: NSNode]
    var methods: [SwiftOp]
    init(path: [String]) {
        self.path = path
        self.children = [:]
        self.methods = []
    }
}

private func emitNamespaceTree(_ ops: [SwiftOp]) -> String {
    let root = NSNode(path: [])
    for op in ops {
        let segs = opSegments(op.operationID)
        var node = root
        let upper = max0(segs.count - 1)
        for seg in segs[0..<upper] {
            if node.children[seg] == nil {
                node.children[seg] = NSNode(path: node.path + [seg])
            }
            node = node.children[seg]!
        }
        node.methods.append(op)
    }

    // BFS collect for deterministic output.
    var all: [NSNode] = []
    var queue: [NSNode] = [root]
    while !queue.isEmpty {
        let n = queue.removeFirst()
        all.append(n)
        let keys = n.children.keys.sorted()
        for k in keys {
            queue.append(n.children[k]!)
        }
    }

    var out = ""
    for node in all {
        out += renderNSNode(node)
        out += "\n"
    }
    return out
}

private func nsTypeName(_ path: [String]) -> String {
    if path.isEmpty {
        return "PalBackendClient"
    }
    return "PB" + path.map { typeNameOf($0) }.joined() + "Namespace"
}

private func renderNSNode(_ node: NSNode) -> String {
    let isRoot = node.path.isEmpty
    var lines: [String] = []
    if isRoot {
        lines.append("public extension PalBackendClient {")
    } else {
        lines.append("public nonisolated struct " + nsTypeName(node.path) + ": Sendable {")
        lines.append("    let _pb: PalBackendClient")
    }
    var vis = "public "
    if isRoot {
        vis = "" // public extension members are implicitly public
    }
    var pbRef = "_pb"
    if isRoot {
        pbRef = "self"
    }

    let keys = node.children.keys.sorted()
    for seg in keys {
        let child = node.children[seg]!
        let ct = nsTypeName(child.path)
        lines.append(indent(1) + vis + "nonisolated var " + identOf(seg) + ": " + ct + " { " + ct + "(_pb: " + pbRef + ") }")
    }

    for op in node.methods {
        let segs = opSegments(op.operationID)
        let method = identOf(segs[segs.count - 1])
        let reqType = requestTypeName(op.operationID)
        let resType = responseTypeName(op.operationID)
        let errEnum = errorEnumName(op.operationID)
        let throwsKw = "throws(" + errEnum + ")"

        // An @Upload op gets a DIFFERENT method shape.
        if op.upload != nil {
            lines.append(contentsOf: renderUploadMethodLines(op, method, reqType, resType, throwsKw, vis, pbRef))
            continue
        }

        var pathParamArgs: [String] = []
        for name in op.pathParams {
            pathParamArgs.append(identOf(name) + ": String")
        }
        var queryParam = ""
        if op.query != nil {
            queryParam = "query: " + queryTypeName(op.operationID)
        }
        var headerParam = ""
        if op.headers != nil {
            headerParam = "headers: " + headersTypeName(op.operationID)
        }
        // joinParams comma-joins the method parameters — path-param args first.
        func joinParams(_ parts: String...) -> String {
            var nonEmpty: [String] = []
            nonEmpty.append(contentsOf: pathParamArgs)
            for p in parts {
                if p != "" {
                    nonEmpty.append(p)
                }
            }
            return nonEmpty.joined(separator: ", ")
        }

        // Endpoint-construction args mirror the struct's memberwise init order.
        var endpointArgs: [String] = []
        for name in op.pathParams {
            let id = identOf(name)
            endpointArgs.append(id + ": " + id)
        }
        if op.input != nil {
            endpointArgs.append("input: input")
        }
        if op.query != nil {
            endpointArgs.append("query: query")
        }
        if op.headers != nil {
            endpointArgs.append("headers: headers")
        }
        let callExpr = endpointStructName(op.operationID) + "(" + endpointArgs.joined(separator: ", ") + ")"

        var inputParam = ""
        if op.input != nil {
            inputParam = "_ input: " + reqType
        }

        if op.sse {
            // A streaming op returns the SEQUENCE, not a value. Untyped `throws`
            // rather than the endpoint's typed error enum: `pb.stream` reports a
            // non-2xx before the stream opens and a mid-stream failure through
            // the stream itself, so there is no single typed error the signature
            // could honestly promise.
            //
            // Cancellation needs no argument: breaking out of the caller's
            // `for try await` tears the stream down, which cancels the request,
            // which fires the server's AbortSignal and stops the provider.
            lines.append(indent(1) + vis + "func " + method + "(" + joinParams(inputParam, queryParam, headerParam) + ") async throws -> AsyncThrowingStream<" + resType + ", Error> {")
            lines.append(indent(2) + "return try await " + pbRef + ".stream(" + callExpr + ")")
        } else if op.output != nil {
            lines.append(indent(1) + "@discardableResult")
            lines.append(indent(1) + vis + "func " + method + "(" + joinParams(inputParam, queryParam, headerParam) + ") async " + throwsKw + " -> " + resType + " {")
            lines.append(indent(2) + "return try await " + pbRef + ".call(" + callExpr + ")")
        } else {
            lines.append(indent(1) + vis + "func " + method + "(" + joinParams(inputParam, queryParam, headerParam) + ") async " + throwsKw + " {")
            lines.append(indent(2) + "try await " + pbRef + ".call(" + callExpr + ")")
        }
        lines.append(indent(1) + "}")
    }

    lines.append("}")
    return lines.joined(separator: "\n") + "\n"
}

// renderUploadMethodLines emits the namespace method for an @Upload op.
private func renderUploadMethodLines(_ op: SwiftOp, _ method: String, _ reqType: String, _ resType: String, _ throwsKw: String, _ vis: String, _ pbRef: String) -> [String] {
    var params: [String] = []
    for name in op.pathParams {
        params.append(identOf(name) + ": String")
    }
    params.append("file: PBFileSource")
    if op.input != nil {
        params.append("input: " + reqType)
    }
    params.append("onProgress: (@Sendable (BackendUploadProgress) -> Void)? = nil")

    var endpointArgs: [String] = []
    for name in op.pathParams {
        let id = identOf(name)
        endpointArgs.append(id + ": " + id)
    }
    if op.input != nil {
        endpointArgs.append("input: input")
    }
    let callExpr = endpointStructName(op.operationID) + "(" + endpointArgs.joined(separator: ", ") + ")"

    var resultType = resType
    if op.output == nil {
        resultType = responseTypeName(op.operationID)
    }

    var lines: [String] = []
    lines.append(indent(1) + "@discardableResult")
    lines.append(indent(1) + vis + "func " + method + "(" + params.joined(separator: ", ") + ") async " + throwsKw + " -> " + resultType + " {")
    lines.append(indent(2) + "return try await " + pbRef + ".call(" + callExpr + ", file: file, onProgress: onProgress)")
    lines.append(indent(1) + "}")
    return lines
}

private func max0(_ n: Int) -> Int {
    if n < 0 {
        return 0
    }
    return n
}
