// swift-tools-version:6.0
import PackageDescription

// palbackend-ios — the managed-backend SDK (binary distribution).
//
// `import Palbe` gives a single entry point `pb`: generated typed endpoint
// calls (`pb.rooms.create(...)`), the untyped escape hatch (`pb.call`/
// `pb.upload`), and auth (`pb.auth.*`). The SDK ships as a closed-source
// XCFramework — `Palbe` is a binaryTarget, so consumers see only the public
// API (Cmd+Click shows no implementation). Source lives in a private repo.
//
// Typed calls are generated by the `palbase` CLI (`palbase backend types
// --lang swift`) from an Xcode Run Script build phase — see README. There is
// no SwiftPM codegen plugin: one path, the CLI.
let package = Package(
    name: "Palbe",
    platforms: [
        .iOS(.v18),
        .macOS(.v15),
    ],
    products: [
        .library(name: "Palbe", targets: ["Palbe", "LiveKitWebRTC", "RustLiveKitUniFFI"]),
        .library(name: "PalbePurchases", targets: ["PalbePurchases"]),
    ],
    targets: [
        .binaryTarget(
            name: "Palbe",
            url: "https://github.com/palgroup/palbackend-ios/releases/download/v0.30.0/Palbe.xcframework.zip",
            checksum: "34d89aa883b725a014d4f8db9c050803e669490c114b16974783bca47803ade1"
        ),
        .binaryTarget(
            name: "PalbePurchases",
            url: "https://github.com/palgroup/palbackend-ios/releases/download/v0.30.0/PalbePurchases.xcframework.zip",
            checksum: "0046cc3a74b2ac41383f5acb951fee89b22e900cf5ed1fe5345806774e7da7bf"
        ),
        .binaryTarget(
            name: "RustLiveKitUniFFI",
            url: "https://github.com/livekit/livekit-uniffi-xcframework/releases/download/0.0.6/RustLiveKitUniFFI.xcframework.zip",
            checksum: "0d3f2ce159a224c728f8b131068d53bbf9b13d968cda0edc68a6a2290f2651ed"
        ),
        .binaryTarget(
            name: "LiveKitWebRTC",
            url: "https://github.com/livekit/webrtc-xcframework/releases/download/144.7559.11/LiveKitWebRTC.xcframework.zip",
            checksum: "07c5caf718058af3c528dcabd257298c40e5a8527e4fb9f47c48336ba5899853"
        ),
        .executableTarget(name: "palbase-swiftgen", path: "Sources/palbase-swiftgen"),
    ],
    swiftLanguageModes: [.v6]
)
