// swift-tools-version:6.0
import PackageDescription

// palbackend-ios — the managed-backend SDK (binary distribution).
//
// `import Palbe` gives a single entry point `pb`: generated typed endpoint
// calls (`pb.rooms.create(...)`), the untyped escape hatch (`pb.call`/
// `pb.upload`), and auth (`pb.auth.*`). The SDK ships as a closed-source
// XCFramework — `Palbe` is a binaryTarget, so consumers see only the public
// API (Cmd+Click shows no implementation). Source lives in a private repo.
//
// Typed calls are generated by the `palbase` CLI (`palbase backend types
// --lang swift`) from an Xcode Run Script build phase — see README. There is
// no SwiftPM codegen plugin: one path, the CLI.
let package = Package(
    name: "Palbe",
    platforms: [
        .iOS(.v18),
        .macOS(.v15),
    ],
    products: [
        .library(name: "Palbe", targets: ["Palbe"]),
        .library(name: "PalbeMessaging", targets: ["Palbe", "PalbeMessaging"]),
        .library(name: "PalbeCall", targets: ["Palbe", "PalbeMessaging", "PalbeCall", "LiveKitWebRTC", "RustLiveKitUniFFI"]),
        .library(name: "PalbePurchases", targets: ["PalbePurchases"]),
    ],
    targets: [
        .binaryTarget(
            name: "Palbe",
            url: "https://github.com/palgroup/palbackend-ios/releases/download/v0.37.0/Palbe.xcframework.zip",
            checksum: "a8f1bd6a6261a412d7a8f4b91a9273058e65d7b729d76e865871e6afdf1d0fd1"
        ),
        .binaryTarget(
            name: "PalbeMessaging",
            url: "https://github.com/palgroup/palbackend-ios/releases/download/v0.37.0/PalbeMessaging.xcframework.zip",
            checksum: "243e96843f836bf35938d081d2ae5099d39d3b5d48cc5db7fe05c38a988d828e"
        ),
        .binaryTarget(
            name: "PalbeCall",
            url: "https://github.com/palgroup/palbackend-ios/releases/download/v0.37.0/PalbeCall.xcframework.zip",
            checksum: "bbc60527143722d4afde295ae296f81c96e09826c6dc1d7ef6eff1ac1bb40cef"
        ),
        .binaryTarget(
            name: "PalbePurchases",
            url: "https://github.com/palgroup/palbackend-ios/releases/download/v0.37.0/PalbePurchases.xcframework.zip",
            checksum: "36adc4b9f8d0da0fd8d456f0f97f728b357a464afc22180b41b7c03d02aab05b"
        ),
        .binaryTarget(
            name: "RustLiveKitUniFFI",
            url: "https://github.com/livekit/livekit-uniffi-xcframework/releases/download/0.0.6/RustLiveKitUniFFI.xcframework.zip",
            checksum: "0d3f2ce159a224c728f8b131068d53bbf9b13d968cda0edc68a6a2290f2651ed"
        ),
        .binaryTarget(
            name: "LiveKitWebRTC",
            url: "https://github.com/livekit/webrtc-xcframework/releases/download/144.7559.11/LiveKitWebRTC.xcframework.zip",
            checksum: "07c5caf718058af3c528dcabd257298c40e5a8527e4fb9f47c48336ba5899853"
        ),
        .executableTarget(name: "palbase-swiftgen", path: "Sources/palbase-swiftgen"),
    ],
    swiftLanguageModes: [.v6]
)
