// swift-tools-version:6.0
import PackageDescription

// palbackend-ios — the managed-backend SDK (binary distribution).
//
// `import Palbe` gives a single entry point `pb`: generated typed endpoint
// calls (`pb.rooms.create(...)`), the untyped escape hatch (`pb.call`/
// `pb.upload`), and auth (`pb.auth.*`). The SDK ships as a closed-source
// XCFramework — `Palbe` is a binaryTarget, so consumers see only the public
// API (Cmd+Click shows no implementation). Source lives in a private repo.
//
// Typed calls are generated by the `palbase` CLI (`palbase backend types
// --lang swift`) from an Xcode Run Script build phase — see README. There is
// no SwiftPM codegen plugin: one path, the CLI.
let package = Package(
    name: "Palbe",
    platforms: [
        .iOS(.v18),
        .macOS(.v15),
    ],
    products: [
        .library(name: "Palbe", targets: ["Palbe"]),
        .library(name: "PalbeMessaging", targets: ["Palbe", "PalbeMessaging"]),
        .library(name: "PalbeCall", targets: ["Palbe", "PalbeMessaging", "PalbeCall", "LiveKitWebRTC", "RustLiveKitUniFFI"]),
        .library(name: "PalbePurchases", targets: ["PalbePurchases"]),
    ],
    targets: [
        .binaryTarget(
            name: "Palbe",
            url: "https://github.com/palgroup/palbackend-ios/releases/download/v0.47.0/Palbe.xcframework.zip",
            checksum: "a27108e672e1242d7f7a7c39b8c78ea2ec2a2035bb8992155476f50d8e9352c5"
        ),
        .binaryTarget(
            name: "PalbeMessaging",
            url: "https://github.com/palgroup/palbackend-ios/releases/download/v0.47.0/PalbeMessaging.xcframework.zip",
            checksum: "70286b676b74fdd4b06dfee0e1bff8836142c8ef4ac1543fd93c4f623c209a80"
        ),
        .binaryTarget(
            name: "PalbeCall",
            url: "https://github.com/palgroup/palbackend-ios/releases/download/v0.47.0/PalbeCall.xcframework.zip",
            checksum: "256f7bc1159e1780820b5959aa7f7a5c6d6e05547dc78dfa87b390acb8c6c51d"
        ),
        .binaryTarget(
            name: "PalbePurchases",
            url: "https://github.com/palgroup/palbackend-ios/releases/download/v0.47.0/PalbePurchases.xcframework.zip",
            checksum: "3dab11f42d2948f4a63125533b8598ec2c51b6cedd4dd206bcef3b13be22bc8e"
        ),
        .binaryTarget(
            name: "RustLiveKitUniFFI",
            url: "https://github.com/livekit/livekit-uniffi-xcframework/releases/download/0.0.6/RustLiveKitUniFFI.xcframework.zip",
            checksum: "0d3f2ce159a224c728f8b131068d53bbf9b13d968cda0edc68a6a2290f2651ed"
        ),
        .binaryTarget(
            name: "LiveKitWebRTC",
            url: "https://github.com/livekit/webrtc-xcframework/releases/download/144.7559.11/LiveKitWebRTC.xcframework.zip",
            checksum: "07c5caf718058af3c528dcabd257298c40e5a8527e4fb9f47c48336ba5899853"
        ),
        .executableTarget(name: "palbase-swiftgen", path: "Sources/palbase-swiftgen"),
    ],
    swiftLanguageModes: [.v6]
)
