import Foundation

// Turns parsed Operations into a single Swift source file that extends the
// PalBackend façade with namespaced, typed methods:
//
//   endpoints/rooms/create.ts  (operationId "rooms.create")
//     → pb.backend.rooms.create(.init(name: "lobby"))  -> Rooms.Create.Output
//
// Generated code is plain Codable + calls the public BackendNamespace.call,
// so it compiles in the consumer app target (which `import PalBackend`).

enum SwiftEmitter {
    /// `auth` is reserved on `pb` (the auth namespace), so a generated endpoint
    /// whose top segment is `auth` would collide. Skip those operations.
    static func usable(_ operations: [Operation]) -> [Operation] {
        operations.filter { Naming.segments($0.operationId).first?.lowercased() != "auth" }
    }

    static func emit(operations rawOperations: [Operation]) -> String {
        let operations = usable(rawOperations)
        var out = """
        // Generated by `palbase backend types` — DO NOT EDIT.
        // Source: palbase.openapi.json. Re-run after every backend deploy.
        import Foundation
        import Palbe


        """

        out += "// MARK: - Request / response types\n\n"
        out += TypeEmitter.renderTypeTree(operations: operations)

        out += "\n// MARK: - Namespaced calls (pb.*)\n\n"
        out += NamespaceTree(operations: operations).render()

        return out
    }
}

// MARK: - Naming

enum Naming {
    static func segments(_ operationId: String) -> [String] {
        operationId.split(separator: ".").map(String.init)
    }
    static func typeName(_ s: String) -> String { sanitize(s, firstUpper: true) }
    static func ident(_ s: String) -> String { escapeKeyword(sanitize(s, firstUpper: false)) }

    /// "rooms.create" → "Rooms.Create"
    static func typePrefix(_ operationId: String) -> String {
        segments(operationId).map(typeName).joined(separator: ".")
    }

    private static func sanitize(_ s: String, firstUpper: Bool) -> String {
        var parts: [String] = []
        var cur = ""
        for ch in s {
            if ch.isLetter || ch.isNumber { cur.append(ch) }
            else if !cur.isEmpty { parts.append(cur); cur = "" }
        }
        if !cur.isEmpty { parts.append(cur) }
        if parts.isEmpty { return firstUpper ? "Op" : "op" }
        var result = ""
        for (i, p) in parts.enumerated() {
            if i == 0 && !firstUpper {
                result += p.prefix(1).lowercased() + p.dropFirst()
            } else {
                result += p.prefix(1).uppercased() + p.dropFirst()
            }
        }
        if let f = result.first, f.isNumber { result = "_" + result }
        return result
    }

    private static let keywords: Set<String> = [
        "class", "struct", "enum", "func", "let", "var", "return", "if", "else",
        "for", "while", "switch", "case", "default", "import", "public", "private",
        "internal", "protocol", "extension", "self", "init", "deinit", "in", "where",
        "as", "is", "try", "throw", "throws", "async", "await", "nil", "true", "false",
        "guard", "defer", "do", "catch", "repeat", "operator", "associatedtype", "any",
    ]
    private static func escapeKeyword(_ id: String) -> String {
        keywords.contains(id) ? "`\(id)`" : id
    }
    static func unbacktick(_ s: String) -> String { s.replacingOccurrences(of: "`", with: "") }
}

// MARK: - Type namespaces (Rooms.Create.Input / .Output)

enum TypeEmitter {
    /// Build a single merged namespace tree of enums so a shared prefix like
    /// `Rooms` is declared once, with each operation's Input/Output types at
    /// its leaf. Emitting per-operation would redeclare `enum Rooms` and fail.
    static func renderTypeTree(operations: [Operation]) -> String {
        final class Node {
            var children: [String: Node] = [:]
            var op: Operation?               // set when this node is an operation leaf
        }
        let root = Node()
        for op in operations {
            let segs = Naming.segments(op.operationId).map(Naming.typeName)
            var node = root
            for seg in segs {
                if let c = node.children[seg] { node = c }
                else { let c = Node(); node.children[seg] = c; node = c }
            }
            node.op = op
        }

        var lines: [String] = []
        func walk(_ name: String, _ node: Node, depth: Int) {
            lines.append(indent(depth) + "public enum \(name) {")
            // Operation leaf: emit Input/Output here.
            if let op = node.op {
                if let input = op.input {
                    lines.append(contentsOf: declLines(name: "Input", schema: input, depth: depth + 1))
                } else {
                    lines.append(indent(depth + 1) + "public typealias Input = EmptyPayload")
                }
                if let output = op.output {
                    lines.append(contentsOf: declLines(name: "Output", schema: output, depth: depth + 1))
                } else {
                    lines.append(indent(depth + 1) + "public typealias Output = EmptyPayload")
                }
            }
            for child in node.children.keys.sorted() {
                walk(child, node.children[child]!, depth: depth + 1)
            }
            lines.append(indent(depth) + "}")
        }
        for top in root.children.keys.sorted() {
            walk(top, root.children[top]!, depth: 0)
        }
        return lines.joined(separator: "\n") + "\n"
    }

    static func indent(_ d: Int) -> String { String(repeating: "    ", count: d) }

    /// Lines for `public struct Name {...}` (object) or a typealias (scalar/array).
    static func declLines(name: String, schema: SchemaNode, depth: Int) -> [String] {
        if case .object(let props) = schema.kind {
            return structLines(name: name, properties: props, depth: depth)
        }
        return [indent(depth) + "public typealias \(name) = \(bareType(schema))"]
    }

    static func structLines(name: String, properties: [(name: String, schema: SchemaNode, required: Bool)], depth: Int) -> [String] {
        var lines: [String] = []
        lines.append(indent(depth) + "public struct \(name): Codable, Sendable {")
        let fd = depth + 1

        struct Field { let ident: String; let key: String; let type: String; let optional: Bool }
        var fields: [Field] = []
        for p in properties {
            let optional = !p.required || p.schema.nullable
            let (type, nested) = fieldType(p.schema, fieldName: p.name, depth: fd)
            lines.append(contentsOf: nested)
            fields.append(Field(ident: Naming.ident(p.name), key: p.name, type: type, optional: optional))
        }
        for f in fields {
            lines.append(indent(fd) + "public let \(f.ident): \(f.optional ? f.type + "?" : f.type)")
        }
        // Memberwise init.
        let params = fields.map { "\($0.ident): \($0.type)\($0.optional ? "? = nil" : "")" }.joined(separator: ", ")
        lines.append(indent(fd) + "public init(\(params)) {")
        for f in fields { lines.append(indent(fd + 1) + "self.\(f.ident) = \(f.ident)") }
        lines.append(indent(fd) + "}")
        // CodingKeys only if any ident was sanitized away from the wire key.
        if fields.contains(where: { Naming.unbacktick($0.ident) != $0.key }) {
            lines.append(indent(fd) + "enum CodingKeys: String, CodingKey {")
            for f in fields {
                if Naming.unbacktick(f.ident) != f.key {
                    lines.append(indent(fd + 1) + "case \(f.ident) = \"\(f.key)\"")
                } else {
                    lines.append(indent(fd + 1) + "case \(f.ident)")
                }
            }
            lines.append(indent(fd) + "}")
        }
        lines.append(indent(depth) + "}")
        return lines
    }

    /// (Swift type, nested decl lines) for a property schema.
    static func fieldType(_ schema: SchemaNode, fieldName: String, depth: Int) -> (String, [String]) {
        switch schema.kind {
        case .string: return ("String", [])
        case .number: return ("Double", [])
        case .integer: return ("Int", [])
        case .boolean: return ("Bool", [])
        case .any: return ("AnyCodableValue", [])
        case .stringEnum(let cases):
            let typeName = Naming.typeName(fieldName) + "Value"
            var decl = [indent(depth) + "public enum \(typeName): String, Codable, Sendable {"]
            for c in cases { decl.append(indent(depth + 1) + "case \(Naming.ident(c)) = \"\(c)\"") }
            decl.append(indent(depth) + "}")
            return (typeName, decl)
        case .array(let element):
            let (elemType, nested) = fieldType(element, fieldName: fieldName + "Item", depth: depth)
            return ("[\(elemType)]", nested)
        case .object(let props):
            let typeName = Naming.typeName(fieldName)
            return (typeName, structLines(name: typeName, properties: props, depth: depth))
        }
    }

    static func bareType(_ schema: SchemaNode) -> String {
        switch schema.kind {
        case .string: return "String"
        case .number: return "Double"
        case .integer: return "Int"
        case .boolean: return "Bool"
        case .any: return "AnyCodableValue"
        case .stringEnum: return "String"
        case .array(let e): return "[\(bareType(e))]"
        case .object: return "AnyCodableValue"
        }
    }
}

// MARK: - Namespace tree → accessor structs + methods

final class NamespaceTree {
    private let operations: [Operation]
    init(operations: [Operation]) { self.operations = operations }

    /// A node in the namespace tree. Root corresponds to BackendNamespace.
    private final class Node {
        var path: [String]
        var children: [String: Node] = [:]
        var methods: [Operation] = []
        init(path: [String]) { self.path = path }
    }

    func render() -> String {
        let root = Node(path: [])
        for op in operations {
            let segs = Naming.segments(op.operationId)
            var node = root
            for seg in segs.dropLast() {
                if let c = node.children[seg] { node = c }
                else { let c = Node(path: node.path + [seg]); node.children[seg] = c; node = c }
            }
            node.methods.append(op)
        }

        var out = ""
        // Collect every node (BFS) so each gets its own type / extension.
        var all: [Node] = []
        var queue = [root]
        while !queue.isEmpty {
            let n = queue.removeFirst()
            all.append(n)
            for key in n.children.keys.sorted() { queue.append(n.children[key]!) }
        }
        for node in all {
            out += renderNode(node) + "\n"
        }
        return out
    }

    /// Struct type name for a namespace node ("rooms.id" → "PBRoomsIdNamespace").
    /// The root is the public `PalBackendClient` (`pb`) itself.
    private func typeName(_ path: [String]) -> String {
        path.isEmpty ? "PalBackendClient" : "PB" + path.map(Naming.typeName).joined() + "Namespace"
    }

    private func renderNode(_ node: Node) -> String {
        let isRoot = node.path.isEmpty
        let typeN = typeName(node.path)
        var lines: [String] = []

        if isRoot {
            // Hang top-level namespaces + any root-level ops directly on `pb`.
            lines.append("public extension PalBackendClient {")
        } else {
            lines.append("public struct \(typeN): Sendable {")
            lines.append("    let _pb: PalBackendClient")
        }
        let d = 1

        // In a `public extension` members are implicitly public; inside a
        // `public struct` they must be marked explicitly.
        let vis = isRoot ? "" : "public "

        // Child namespace accessors (sorted for determinism).
        for seg in node.children.keys.sorted() {
            let child = node.children[seg]!
            let childType = typeName(child.path)
            let accessor = Naming.ident(seg)
            let pbRef = isRoot ? "self" : "_pb"
            lines.append(TypeEmitter.indent(d) + "\(vis)var \(accessor): \(childType) { \(childType)(_pb: \(pbRef)) }")
        }

        // Leaf methods.
        for op in node.methods {
            lines.append(contentsOf: methodLines(op, indent: d, isRoot: isRoot))
        }

        lines.append("}")
        return lines.joined(separator: "\n") + "\n"
    }

    private func methodLines(_ op: Operation, indent d: Int, isRoot: Bool) -> [String] {
        let method = Naming.ident(Naming.segments(op.operationId).last ?? "call")
        let typePrefix = Naming.typePrefix(op.operationId)
        let pbRef = isRoot ? "self" : "_pb"
        let vis = isRoot ? "" : "public "
        let ind = TypeEmitter.indent(d)
        let hasInput = op.input != nil

        var lines: [String] = []
        lines.append(ind + "@discardableResult")
        if hasInput {
            lines.append(ind + "\(vis)func \(method)(_ input: \(typePrefix).Input) async throws(BackendError) -> \(typePrefix).Output {")
            lines.append(ind + "    try await \(pbRef)._invoke(\"\(op.operationId)\", input, as: \(typePrefix).Output.self)")
        } else {
            lines.append(ind + "\(vis)func \(method)() async throws(BackendError) -> \(typePrefix).Output {")
            lines.append(ind + "    try await \(pbRef)._invoke(\"\(op.operationId)\", EmptyPayload(), as: \(typePrefix).Output.self)")
        }
        lines.append(ind + "}")
        return lines
    }
}
